spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: http://ecommerce-product-service:8083
              predicates:
                - Path=/products/**

            - id: order-service
              uri: http://ecommerce-order-service:8081
              predicates:
                - Path=/orders/**

            - id: payment-service
              uri: http://ecommerce-payment-service:8082
              predicates:
                - Path=/payments/**

            - id: auth-service
              uri: http://ecommerce-auth-service:8084
              predicates:
                - Path=/users/**,/auth/**

server:
  port: 8080